### ISSUE TITLE
"from base import *" in settings/local.py does not work

### ISSUE THREAD

**Issue by tiagofassoni** [jcalazan/django-project-template#2]
In my computer, at least, with Python 3.4

My solution was to change

``` python
from base import *
```

 to:

``` python
from project_name.settings.base import *
```

I did not make that change in a pull request because that might be happening by some stupidity of mine.

**Comment by jcalazan** [comment]
I'm still on 2.7, but will try this on my project later tonight and will make the change if it still works.  Thanks!

**Comment by jcalazan** [comment]
Pushed the changes so import is compatible with Python 3, thanks!
